### ISSUE TITLE
Comment on Comments

### ISSUE THREAD

**Issue by nnnnicholas** [jbx-protocol/juice-buyback#4]
I'm not sure what this comment means. Could be clarified?

https://github.com/jbx-protocol/juice-buyback/blob/7536d9379ecb9fb0b0d2fbde57b3ed9eae72784f/contracts/JBXBuybackDelegate.sol#L58

**Comment by viraj124** [comment]
It's a address comparison to set token 0 & token 1 as in the uniswap pool
